project:
  type: website
  output-dir: docs

website:
  title: "Energiek Twenterand"
  navbar:
    logo: "images/energiektwenterand.png"
    left:
      - href: index.qmd
        text: Begin
      - href: about.qmd
        text: Ons verhaal
      - href: contact.qmd
        text: Contact

format:
  html:
    theme:
        light: flatly
        dark: darkly
    css: styles.css
    toc: true



