project:
  type: website
  output-dir: docs

website:
  title: "Energiek Twenterand"
  navbar:
    logo: "images/energiektwenterand.png"
    left:
      - href: index.qmd
        text: Begin
      - href: about.qmd
        text: Ons verhaal
      - href: blog.qmd
        text: Blog
      - href: documenten.qmd
        text: Documenten
      - href: contact.qmd
        text: Contact
        

format:
  html:
    theme:  [flatly, assets/styling/theme.scss]
    css: styles.css
    toc: true
    pagetitle: "Energiek TWenterand | {{< meta title >}}"



